"""initial schema

Revision ID: 72a42d1403fa
Revises: 
Create Date: 2026-05-31 16:53:32.957150+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72a42d1403fa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'operator', 'admin', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assets',
    sa.Column('short_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('host', 'network_device', 'service', 'software_license', 'cloud_resource', name='assettype', native_enum=False, length=32), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('provisioning', 'active', 'maintenance', 'retired', 'disposed', name='lifecyclestate', native_enum=False, length=20), nullable=False),
    sa.Column('environment', sa.Enum('prod', 'staging', 'dev', name='environment', native_enum=False, length=16), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_assets_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_assets_short_code'), 'assets', ['short_code'], unique=True)
    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'state_change', 'checkout', 'checkin', name='auditaction', native_enum=False, length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_entity_recent', 'audit_log', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('compliance_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=True),
    sa.Column('total_assets', sa.Integer(), nullable=False),
    sa.Column('org_score', sa.Float(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_count', sa.Integer(), nullable=False),
    sa.Column('severity_failing', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_compliance_runs_triggered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_runs'))
    )
    op.create_index(op.f('ix_compliance_runs_started_at'), 'compliance_runs', ['started_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('asset_checkouts',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('holder_id', sa.Uuid(), nullable=True),
    sa.Column('checked_out_by_id', sa.Uuid(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_checkouts_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['users.id'], name=op.f('fk_asset_checkouts_checked_out_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['holder_id'], ['users.id'], name=op.f('fk_asset_checkouts_holder_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_checkouts'))
    )
    op.create_index(op.f('ix_asset_checkouts_asset_id'), 'asset_checkouts', ['asset_id'], unique=False)
    op.create_index('ix_checkout_asset_active', 'asset_checkouts', ['asset_id', 'checked_in_at'], unique=False)
    op.create_table('asset_dependencies',
    sa.Column('source_asset_id', sa.Uuid(), nullable=False),
    sa.Column('target_asset_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_asset_id <> target_asset_id', name=op.f('ck_asset_dependencies_no_self_dependency')),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], name=op.f('fk_asset_dependencies_source_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], name=op.f('fk_asset_dependencies_target_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_dependencies')),
    sa.UniqueConstraint('source_asset_id', 'target_asset_id', name='dependency_edge')
    )
    op.create_index(op.f('ix_asset_dependencies_source_asset_id'), 'asset_dependencies', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_dependencies_target_asset_id'), 'asset_dependencies', ['target_asset_id'], unique=False)
    op.create_table('asset_tags',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_tags_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_asset_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id', name=op.f('pk_asset_tags'))
    )
    op.create_table('compliance_results',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('passed', 'failed', 'not_applicable', name='compliancestatus', native_enum=False, length=20), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_compliance_results_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['compliance_runs.id'], name=op.f('fk_compliance_results_run_id_compliance_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_results'))
    )
    op.create_index(op.f('ix_compliance_results_asset_id'), 'compliance_results', ['asset_id'], unique=False)
    op.create_index('ix_compliance_results_asset_recent', 'compliance_results', ['asset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_compliance_results_rule_id'), 'compliance_results', ['rule_id'], unique=False)
    op.create_index('ix_compliance_results_run_asset', 'compliance_results', ['run_id', 'asset_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_run_id'), 'compliance_results', ['run_id'], unique=False)
    op.create_table('services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('slo_target', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_services_asset_id_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_asset_id'), 'services', ['asset_id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('health_checks',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('check_type', sa.Enum('http', 'tcp', name='checktype', native_enum=False, length=8), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('expected_status', sa.Integer(), nullable=False),
    sa.Column('latency_budget_ms', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_health_checks_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_checks'))
    )
    op.create_index(op.f('ix_health_checks_service_id'), 'health_checks', ['service_id'], unique=False)
    op.create_table('check_results',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('health_check_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('up', 'down', name='checkstatus', native_enum=False, length=8), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['health_check_id'], ['health_checks.id'], name=op.f('fk_check_results_health_check_id_health_checks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_results'))
    )
    op.create_index('ix_check_results_check_recent', 'check_results', ['health_check_id', 'created_at'], unique=False)
    op.create_table('incidents',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('health_check_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', 'closed', name='incidentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_incidents_acknowledged_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_incidents_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['health_check_id'], ['health_checks.id'], name=op.f('fk_incidents_health_check_id_health_checks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_incidents_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_incidents_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_asset_id'), 'incidents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_incidents_opened_at'), 'incidents', ['opened_at'], unique=False)
    op.create_index(op.f('ix_incidents_service_id'), 'incidents', ['service_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_opened', 'incidents', ['status', 'opened_at'], unique=False)
    op.create_table('ai_triage_results',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('success', 'disabled', 'failed', name='triagestatus', native_enum=False, length=12), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('root_cause_hypothesis', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity_assessment', sa.Enum('low', 'medium', 'high', 'critical', name='severity', native_enum=False, length=16), nullable=True),
    sa.Column('remediation_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stakeholder_comms_draft', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('is_seeded', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_ai_triage_results_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_triage_results'))
    )
    op.create_index(op.f('ix_ai_triage_results_created_at'), 'ai_triage_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_triage_results_incident_id'), 'ai_triage_results', ['incident_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('opened', 'ai_triaged', 'acknowledged', 'comment', 'resolved', 'closed', 'recovered', name='incidenteventtype', native_enum=False, length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_incident_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events'))
    )
    op.create_index(op.f('ix_incident_events_created_at'), 'incident_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_created_at'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_ai_triage_results_incident_id'), table_name='ai_triage_results')
    op.drop_index(op.f('ix_ai_triage_results_created_at'), table_name='ai_triage_results')
    op.drop_table('ai_triage_results')
    op.drop_index('ix_incidents_status_opened', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_service_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_opened_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_asset_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_check_results_check_recent', table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_health_checks_service_id'), table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_asset_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_compliance_results_run_id'), table_name='compliance_results')
    op.drop_index('ix_compliance_results_run_asset', table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_rule_id'), table_name='compliance_results')
    op.drop_index('ix_compliance_results_asset_recent', table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_asset_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_table('asset_tags')
    op.drop_index(op.f('ix_asset_dependencies_target_asset_id'), table_name='asset_dependencies')
    op.drop_index(op.f('ix_asset_dependencies_source_asset_id'), table_name='asset_dependencies')
    op.drop_table('asset_dependencies')
    op.drop_index('ix_checkout_asset_active', table_name='asset_checkouts')
    op.drop_index(op.f('ix_asset_checkouts_asset_id'), table_name='asset_checkouts')
    op.drop_table('asset_checkouts')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_compliance_runs_started_at'), table_name='compliance_runs')
    op.drop_table('compliance_runs')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index('ix_audit_entity_recent', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_assets_short_code'), table_name='assets')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
